name: push-to-EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: check docker version
      run: docker --version

    - name: run docker container
      run: docker run -itd --name nginx -p 80:80 nginx

    - name: execute shell script
      run: sh script.sh
