name: push-to-EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: check docker version
      run: sudo docker --version

    - name: run docker container
      run: sudo docker pull centos

    - name: run docker container
      run: sudo docker run -itd --name centos centos

